export const fakeMaleCharactersSecond = {
  info: {
    count: 610,
    pages: 31,
    next: "https://rickandmortyapi.com/api/character/?page=3&gender=male",
    prev: "https://rickandmortyapi.com/api/character/?page=1&gender=male",
  },
  results: [
    {
      id: 27,
      name: "Artist Morty",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/27.jpeg",
      episode: [
        "https://rickandmortyapi.com/api/episode/10",
        "https://rickandmortyapi.com/api/episode/28",
      ],
      url: "https://rickandmortyapi.com/api/character/27",
      created: "2017-11-05T08:59:07.457Z",
    },
    {
      id: 28,
      name: "Attila Starwar",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "Interdimensional Cable",
        url: "https://rickandmortyapi.com/api/location/6",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/28.jpeg",
      episode: [
        "https://rickandmortyapi.com/api/episode/8",
        "https://rickandmortyapi.com/api/episode/13",
        "https://rickandmortyapi.com/api/episode/17",
      ],
      url: "https://rickandmortyapi.com/api/character/28",
      created: "2017-11-05T09:02:16.595Z",
    },
    {
      id: 29,
      name: "Baby Legs",
      status: "Alive",
      species: "Human",
      type: "Human with baby legs",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "Interdimensional Cable",
        url: "https://rickandmortyapi.com/api/location/6",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/29.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/8"],
      url: "https://rickandmortyapi.com/api/character/29",
      created: "2017-11-05T09:06:19.644Z",
    },
    {
      id: 30,
      name: "Baby Poopybutthole",
      status: "Alive",
      species: "Poopybutthole",
      type: "",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "unknown",
        url: "",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/30.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/31"],
      url: "https://rickandmortyapi.com/api/character/30",
      created: "2017-11-05T09:13:16.483Z",
    },
    {
      id: 31,
      name: "Baby Wizard",
      status: "Dead",
      species: "Alien",
      type: "Parasite",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "Earth (Replacement Dimension)",
        url: "https://rickandmortyapi.com/api/location/20",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/31.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/15"],
      url: "https://rickandmortyapi.com/api/character/31",
      created: "2017-11-05T09:15:11.286Z",
    },
    {
      id: 33,
      name: "Beebo",
      status: "Dead",
      species: "Alien",
      type: "",
      gender: "Male",
      origin: {
        name: "Venzenulon 7",
        url: "https://rickandmortyapi.com/api/location/10",
      },
      location: {
        name: "Venzenulon 7",
        url: "https://rickandmortyapi.com/api/location/10",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/33.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/29"],
      url: "https://rickandmortyapi.com/api/character/33",
      created: "2017-11-05T09:21:55.595Z",
    },
    {
      id: 34,
      name: "Benjamin",
      status: "Alive",
      species: "Poopybutthole",
      type: "",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "Interdimensional Cable",
        url: "https://rickandmortyapi.com/api/location/6",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/34.jpeg",
      episode: [
        "https://rickandmortyapi.com/api/episode/8",
        "https://rickandmortyapi.com/api/episode/13",
        "https://rickandmortyapi.com/api/episode/17",
      ],
      url: "https://rickandmortyapi.com/api/character/34",
      created: "2017-11-05T09:24:04.748Z",
    },
    {
      id: 42,
      name: "Big Head Morty",
      status: "unknown",
      species: "Human",
      type: "Human with giant head",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/42.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/22"],
      url: "https://rickandmortyapi.com/api/character/42",
      created: "2017-11-05T10:15:53.349Z",
    },
    {
      id: 43,
      name: "Big Morty",
      status: "Dead",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/43.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/28"],
      url: "https://rickandmortyapi.com/api/character/43",
      created: "2017-11-05T10:17:04.997Z",
    },
    {
      id: 44,
      name: "Body Guard Morty",
      status: "Dead",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/44.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/28"],
      url: "https://rickandmortyapi.com/api/character/44",
      created: "2017-11-05T10:18:11.062Z",
    },
    {
      id: 45,
      name: "Bill",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Earth (C-137)",
        url: "https://rickandmortyapi.com/api/location/1",
      },
      location: {
        name: "Earth (C-137)",
        url: "https://rickandmortyapi.com/api/location/1",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/45.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/3"],
      url: "https://rickandmortyapi.com/api/character/45",
      created: "2017-11-05T10:22:27.446Z",
    },
    {
      id: 46,
      name: "Bill",
      status: "unknown",
      species: "Animal",
      type: "Dog",
      gender: "Male",
      origin: {
        name: "Earth (Replacement Dimension)",
        url: "https://rickandmortyapi.com/api/location/20",
      },
      location: {
        name: "unknown",
        url: "",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/46.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/2"],
      url: "https://rickandmortyapi.com/api/character/46",
      created: "2017-11-05T10:24:38.089Z",
    },
    {
      id: 47,
      name: "Birdperson",
      status: "Alive",
      species: "Alien",
      type: "Bird-Person",
      gender: "Male",
      origin: {
        name: "Bird World",
        url: "https://rickandmortyapi.com/api/location/15",
      },
      location: {
        name: "Planet Squanch",
        url: "https://rickandmortyapi.com/api/location/35",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/47.jpeg",
      episode: [
        "https://rickandmortyapi.com/api/episode/11",
        "https://rickandmortyapi.com/api/episode/16",
        "https://rickandmortyapi.com/api/episode/21",
        "https://rickandmortyapi.com/api/episode/22",
        "https://rickandmortyapi.com/api/episode/26",
        "https://rickandmortyapi.com/api/episode/49",
        "https://rickandmortyapi.com/api/episode/51",
      ],
      url: "https://rickandmortyapi.com/api/character/47",
      created: "2017-11-05T11:13:36.018Z",
    },
    {
      id: 48,
      name: "Black Rick",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/48.jpeg",
      episode: [
        "https://rickandmortyapi.com/api/episode/22",
        "https://rickandmortyapi.com/api/episode/28",
      ],
      url: "https://rickandmortyapi.com/api/character/48",
      created: "2017-11-05T11:15:26.044Z",
    },
    {
      id: 50,
      name: "Blim Blam",
      status: "Alive",
      species: "Alien",
      type: "Korblock",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "Earth (Replacement Dimension)",
        url: "https://rickandmortyapi.com/api/location/20",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/50.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/14"],
      url: "https://rickandmortyapi.com/api/character/50",
      created: "2017-11-05T11:21:43.756Z",
    },
    {
      id: 51,
      name: "Blue Diplomat",
      status: "Alive",
      species: "Alien",
      type: "",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "Interdimensional Cable",
        url: "https://rickandmortyapi.com/api/location/6",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/51.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/19"],
      url: "https://rickandmortyapi.com/api/character/51",
      created: "2017-11-05T11:24:49.688Z",
    },
    {
      id: 52,
      name: "Blue Footprint Guy",
      status: "Dead",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Post-Apocalyptic Earth",
        url: "https://rickandmortyapi.com/api/location/8",
      },
      location: {
        name: "Post-Apocalyptic Earth",
        url: "https://rickandmortyapi.com/api/location/8",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/52.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/23"],
      url: "https://rickandmortyapi.com/api/character/52",
      created: "2017-11-05T11:26:42.084Z",
    },
    {
      id: 53,
      name: "Blue Shirt Morty",
      status: "unknown",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/53.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/10"],
      url: "https://rickandmortyapi.com/api/character/53",
      created: "2017-11-05T11:28:38.627Z",
    },
    {
      id: 54,
      name: "Bobby Moynihan",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "Interdimensional Cable",
        url: "https://rickandmortyapi.com/api/location/6",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/54.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/8"],
      url: "https://rickandmortyapi.com/api/character/54",
      created: "2017-11-05T11:31:26.348Z",
    },
    {
      id: 56,
      name: "Bootleg Portal Chemist Rick",
      status: "Dead",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "unknown",
        url: "",
      },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/56.jpeg",
      episode: ["https://rickandmortyapi.com/api/episode/28"],
      url: "https://rickandmortyapi.com/api/character/56",
      created: "2017-11-05T11:34:16.447Z",
    },
  ],
};
