export const fakeEpisodesSecond = {
  info: {
    count: 51,
    pages: 3,
    next: "https://rickandmortyapi.com/api/episode/?page=3",
    prev: "https://rickandmortyapi.com/api/episode/?page=1",
  },
  results: [
    {
      id: 21,
      name: "The Wedding Squanchers",
      air_date: "October 4, 2015",
      episode: "S02E10",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/5",
        "https://rickandmortyapi.com/api/character/23",
        "https://rickandmortyapi.com/api/character/47",
      ],
      url: "https://rickandmortyapi.com/api/episode/21",
      created: "2017-11-10T12:56:35.875Z",
    },
    {
      id: 22,
      name: "The Rickshank Rickdemption",
      air_date: "April 1, 2017",
      episode: "S03E01",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/5",
        "https://rickandmortyapi.com/api/character/21",
        "https://rickandmortyapi.com/api/character/22",
      ],
      url: "https://rickandmortyapi.com/api/episode/22",
      created: "2017-11-10T12:56:35.983Z",
    },
    {
      id: 23,
      name: "Rickmancing the Stone",
      air_date: "July 30, 2017",
      episode: "S03E02",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
      ],
      url: "https://rickandmortyapi.com/api/episode/23",
      created: "2017-11-10T12:56:36.100Z",
    },
    {
      id: 24,
      name: "Pickle Rick",
      air_date: "August 6, 2017",
      episode: "S03E03",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/9",
        "https://rickandmortyapi.com/api/character/70",
      ],
      url: "https://rickandmortyapi.com/api/episode/24",
      created: "2017-11-10T12:56:36.206Z",
    },
    {
      id: 25,
      name: "Vindicators 3: The Return of Worldender",
      air_date: "August 13, 2017",
      episode: "S03E04",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/10",
        "https://rickandmortyapi.com/api/character/23",
        "https://rickandmortyapi.com/api/character/35",
        "https://rickandmortyapi.com/api/character/60",
        "https://rickandmortyapi.com/api/character/81",
        "https://rickandmortyapi.com/api/character/88",
        "https://rickandmortyapi.com/api/character/93",
        "https://rickandmortyapi.com/api/character/104",
      ],
      url: "https://rickandmortyapi.com/api/episode/25",
      created: "2017-11-10T12:56:36.310Z",
    },
    {
      id: 26,
      name: "The Whirly Dirly Conspiracy",
      air_date: "August 20, 2017",
      episode: "S03E05",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/5",
        "https://rickandmortyapi.com/api/character/23",
      ],
      url: "https://rickandmortyapi.com/api/episode/26",
      created: "2017-11-10T12:56:36.413Z",
    },
    {
      id: 27,
      name: "Rest and Ricklaxation",
      air_date: "August 27, 2017",
      episode: "S03E06",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/6",
        "https://rickandmortyapi.com/api/character/124",
      ],
      url: "https://rickandmortyapi.com/api/episode/27",
      created: "2017-11-10T12:56:36.515Z",
    },
    {
      id: 28,
      name: "The Ricklantis Mixup",
      air_date: "September 10, 2017",
      episode: "S03E07",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/8",
        "https://rickandmortyapi.com/api/character/18",
        "https://rickandmortyapi.com/api/character/22",
        "https://rickandmortyapi.com/api/character/27",
        "https://rickandmortyapi.com/api/character/43",
        "https://rickandmortyapi.com/api/character/44",
      ],
      url: "https://rickandmortyapi.com/api/episode/28",
      created: "2017-11-10T12:56:36.618Z",
    },
    {
      id: 29,
      name: "Morty's Mind Blowers",
      air_date: "September 17, 2017",
      episode: "S03E08",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/5",
      ],
      url: "https://rickandmortyapi.com/api/episode/29",
      created: "2017-11-10T12:56:36.726Z",
    },
    {
      id: 30,
      name: "The ABC's of Beth",
      air_date: "September 24, 2017",
      episode: "S03E09",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/5",
        "https://rickandmortyapi.com/api/character/58",
        "https://rickandmortyapi.com/api/character/180",
      ],
      url: "https://rickandmortyapi.com/api/episode/30",
      created: "2017-11-10T12:56:36.828Z",
    },
    {
      id: 31,
      name: "The Rickchurian Mortydate",
      air_date: "October 1, 2017",
      episode: "S03E10",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/5",
        "https://rickandmortyapi.com/api/character/13",
      ],
      url: "https://rickandmortyapi.com/api/episode/31",
      created: "2017-11-10T12:56:36.929Z",
    },
    {
      id: 32,
      name: "Edge of Tomorty: Rick, Die, Rickpeat",
      air_date: "November 10, 2019",
      episode: "S04E01",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/5",
      ],
      url: "https://rickandmortyapi.com/api/episode/32",
      created: "2020-04-30T06:52:04.495Z",
    },
    {
      id: 33,
      name: "The Old Man and the Seat",
      air_date: "November 17, 2019",
      episode: "S04E02",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/5",
        "https://rickandmortyapi.com/api/character/525",
        "https://rickandmortyapi.com/api/character/526",
        "https://rickandmortyapi.com/api/character/527",
      ],
      url: "https://rickandmortyapi.com/api/episode/33",
      created: "2020-04-30T06:52:04.498Z",
    },
    {
      id: 34,
      name: "One Crew Over the Crewcoo's Morty",
      air_date: "November 24, 2019",
      episode: "S04E03",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/244",
      ],
      url: "https://rickandmortyapi.com/api/episode/34",
      created: "2020-04-30T06:52:04.498Z",
    },
    {
      id: 35,
      name: "Claw and Hoarder: Special Ricktim's Morty",
      air_date: "December 8, 2019",
      episode: "S04E04",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/5",
        "https://rickandmortyapi.com/api/character/562",
      ],
      url: "https://rickandmortyapi.com/api/episode/35",
      created: "2020-04-30T06:52:04.498Z",
    },
    {
      id: 36,
      name: "Rattlestar Ricklactica",
      air_date: "December 15, 2019",
      episode: "S04E05",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/5",
        "https://rickandmortyapi.com/api/character/251",
        "https://rickandmortyapi.com/api/character/313",
        "https://rickandmortyapi.com/api/character/365",
        "https://rickandmortyapi.com/api/character/571",
      ],
      url: "https://rickandmortyapi.com/api/episode/36",
      created: "2020-04-30T06:52:04.499Z",
    },
    {
      id: 37,
      name: "Never Ricking Morty",
      air_date: "May 3, 2020",
      episode: "S04E06",
      characters: [
        "https://rickandmortyapi.com/api/character/593",
        "https://rickandmortyapi.com/api/character/594",
        "https://rickandmortyapi.com/api/character/595",
        "https://rickandmortyapi.com/api/character/596",
        "https://rickandmortyapi.com/api/character/597",
        "https://rickandmortyapi.com/api/character/598",
        "https://rickandmortyapi.com/api/character/599",
        "https://rickandmortyapi.com/api/character/600",
      ],
      url: "https://rickandmortyapi.com/api/episode/37",
      created: "2020-08-06T05:44:21.422Z",
    },
    {
      id: 38,
      name: "Promortyus",
      air_date: "May 10, 2020",
      episode: "S04E07",
      characters: [
        "https://rickandmortyapi.com/api/character/640",
        "https://rickandmortyapi.com/api/character/641",
        "https://rickandmortyapi.com/api/character/642",
        "https://rickandmortyapi.com/api/character/643",
        "https://rickandmortyapi.com/api/character/644",
        "https://rickandmortyapi.com/api/character/645",
        "https://rickandmortyapi.com/api/character/646",
      ],
      url: "https://rickandmortyapi.com/api/episode/38",
      created: "2020-08-06T05:49:40.563Z",
    },
    {
      id: 39,
      name: "The Vat of Acid Episode",
      air_date: "May 17, 2020",
      episode: "S04E08",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/5",
        "https://rickandmortyapi.com/api/character/240",
        "https://rickandmortyapi.com/api/character/180",
        "https://rickandmortyapi.com/api/character/648",
      ],
      url: "https://rickandmortyapi.com/api/episode/39",
      created: "2020-08-06T05:51:07.419Z",
    },
    {
      id: 40,
      name: "Childrick of Mort",
      air_date: "May 24, 2020",
      episode: "S04E09",
      characters: [
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/3",
        "https://rickandmortyapi.com/api/character/4",
        "https://rickandmortyapi.com/api/character/5",
        "https://rickandmortyapi.com/api/character/662",
        "https://rickandmortyapi.com/api/character/663",
        "https://rickandmortyapi.com/api/character/664",
        "https://rickandmortyapi.com/api/character/665",
        "https://rickandmortyapi.com/api/character/666",
      ],
      url: "https://rickandmortyapi.com/api/episode/40",
      created: "2020-08-06T05:51:25.458Z",
    },
  ],
};
